"""仅 ChatGPT 网页端普通会话；默认不启动任何生产发送，禁止 Codex/API 替代。"""
from config.env_loader import apply_env_overrides
CONVERSATION_POOL_ENABLE = False
CONVERSATION_POOL_TIMEOUT = 30
CONVERSATION_POOL_DEFAULT_TEMPLATE = ""
DEFAULT_CONVERSATION_TEMPLATE = CONVERSATION_POOL_DEFAULT_TEMPLATE  # 用户配置名兼容别名
PROTOCOL_CONVERSATION_ENABLE = False  # 仅 HAR 契约验证后才允许真实发送

# ---- 风控抑制（拟人化节奏）----
# 两条消息之间的随机等待秒数区间：模拟真人读完回答再发问。
# 对齐 chatgpt2api 实测节奏：生产路径硬性保证 >=30 秒（service 层兜底钳制），
# 调低会更快但更像机器人；测试可显式传 message_delay=lambda: 0 关闭等待。
CONVERSATION_POOL_MESSAGE_DELAY_MIN = 32
CONVERSATION_POOL_MESSAGE_DELAY_MAX = 45
# 注册成功后、自动开跑前的随机等待秒数区间：避免"注册完立刻连发 5 条"的机器特征。
CONVERSATION_POOL_START_DELAY_MIN = 45
CONVERSATION_POOL_START_DELAY_MAX = 180
# 手动点"运行"时的启动抖动秒数区间（比注册后自动开跑短，兼顾体验）。
CONVERSATION_POOL_MANUAL_START_DELAY_MIN = 2
CONVERSATION_POOL_MANUAL_START_DELAY_MAX = 8
# 会话是否保存进历史记录：False=普通会话（网页端左侧可见，推荐，更像真实用户）；
# True=临时聊天（服务端不留痕、不可回查）。
CONVERSATION_POOL_HISTORY_DISABLED = False

apply_env_overrides(globals(), {
    "CONVERSATION_POOL_ENABLE": "bool",
    "CONVERSATION_POOL_TIMEOUT": "int",
    "CONVERSATION_POOL_DEFAULT_TEMPLATE": "str",
    "DEFAULT_CONVERSATION_TEMPLATE": "str",
    "PROTOCOL_CONVERSATION_ENABLE": "bool",
    "CONVERSATION_POOL_MESSAGE_DELAY_MIN": "int",
    "CONVERSATION_POOL_MESSAGE_DELAY_MAX": "int",
    "CONVERSATION_POOL_START_DELAY_MIN": "int",
    "CONVERSATION_POOL_START_DELAY_MAX": "int",
    "CONVERSATION_POOL_MANUAL_START_DELAY_MIN": "int",
    "CONVERSATION_POOL_MANUAL_START_DELAY_MAX": "int",
    "CONVERSATION_POOL_HISTORY_DISABLED": "bool",
})
if DEFAULT_CONVERSATION_TEMPLATE: CONVERSATION_POOL_DEFAULT_TEMPLATE = DEFAULT_CONVERSATION_TEMPLATE
